[module.hugoVersion]
min = "0.110.0"

[[module.imports]]
path = "github.com/hugomods/icons/vendors/bootstrap"

[[module.imports]]
path = "github.com/hugomods/images"

[[module.imports]]
path = "github.com/hugomods/base"

[params.bootstrap.config_toggle]
langs = ["toml", "yaml", "json"]

[params.bootstrap.article_cards]
limit = 12
image_height = 240